/* PoseForge 2D v0.11 semantic depth + limb-chain contact */
(function(){
'use strict';
var lang=function(){return window.PoseForgeI18n&&window.PoseForgeI18n.lang?window.PoseForgeI18n.lang():'bn';};
var msg=function(bn,en){return lang()==='bn'?bn:en;};
var ownerFor=function(l){return typeof personOwner==='function'?personOwner(l):(l&&l.kind==='character'?l:state.layers.find(function(x){return x.id===(l&&l.ownerId);})||l);};
var pose=function(l){return l&&l.aiAnalysis&&l.aiAnalysis.poses&&l.aiAnalysis.poses[0]||null;};
var pt=function(l,i){var p=pose(l)&&pose(l)[i];return p?{x:p.x*l.width,y:p.y*l.height}:null;};
var d=function(a,b){return a&&b?Math.hypot(a.x-b.x,a.y-b.y):0;};
var regs=function(l){return window.PoseForgeBodyRegions&&window.PoseForgeBodyRegions.bodyRegions?window.PoseForgeBodyRegions.bodyRegions(l):null;};
var rkey=function(){return ($('#easyRegionSelect')&&$('#easyRegionSelect').value)||'whole';};
var target=function(){return state.layers.find(function(x){return x.id===(($('#occlusionTarget')&&$('#occlusionTarget').value)||'');});};
var feather=function(){return Number(($('#depthFeatherCtrl')&&$('#depthFeatherCtrl').value)||7);};
var maskCache=new Map();
function commit(s){pushHistory(s);renderUI();draw();autoSave();}
function mesh(l){if(!l.mesh)createMeshForLayer(l,9);return l.mesh;}
function invalidate(l){l.meshRev=(l.meshRev||0)+1;if(typeof meshRenderCache!=='undefined')meshRenderCache.delete(l);}
function family(o){return [o].concat(state.layers.filter(function(x){return x.ownerId===o.id&&!x.semanticDepthPass;}));}
function moveRelative(o,t,front){if(!o||!t||o.id===t.id)return false;var f=family(o),ids=new Set(f.map(function(x){return x.id;}));state.layers=state.layers.filter(function(x){return !ids.has(x.id);});var i=state.layers.findIndex(function(x){return x.id===t.id;});if(i<0){state.layers.push.apply(state.layers,f);return false;}state.layers.splice.apply(state.layers,[front?i+1:i,0].concat(f));return true;}
var outward={lUpperArm:['lUpperArm','lForearm','lHand'],rUpperArm:['rUpperArm','rForearm','rHand'],lForearm:['lForearm','lHand'],rForearm:['rForearm','rHand'],lThigh:['lThigh','lLowerLeg','lFoot'],rThigh:['rThigh','rLowerLeg','rFoot'],lLowerLeg:['lLowerLeg','lFoot'],rLowerLeg:['rLowerLeg','rFoot']};
var wholeLimb={lUpperArm:['lUpperArm','lForearm','lHand'],lForearm:['lUpperArm','lForearm','lHand'],lHand:['lUpperArm','lForearm','lHand'],rUpperArm:['rUpperArm','rForearm','rHand'],rForearm:['rUpperArm','rForearm','rHand'],rHand:['rUpperArm','rForearm','rHand'],lThigh:['lThigh','lLowerLeg','lFoot'],lLowerLeg:['lThigh','lLowerLeg','lFoot'],lFoot:['lThigh','lLowerLeg','lFoot'],rThigh:['rThigh','rLowerLeg','rFoot'],rLowerLeg:['rThigh','rLowerLeg','rFoot'],rFoot:['rThigh','rLowerLeg','rFoot']};
function depthKeys(){var k=rkey(),m=($('#depthChainMode')&&$('#depthChainMode').value)||'region';if(k==='whole')return[];if(m==='outward'&&outward[k])return outward[k].slice();if(m==='limb'&&wholeLimb[k])return wholeLimb[k].slice();return[k];}
var seg={lUpperArm:[11,13],rUpperArm:[12,14],lForearm:[13,15],rForearm:[14,16],lThigh:[23,25],rThigh:[24,26],lLowerLeg:[25,27],rLowerLeg:[26,28]};
function paintRegion(g,o,k){var rr=regs(o)&&regs(o)[k];if(!rr)return;if(seg[k]){var a=pt(o,seg[k][0]),b=pt(o,seg[k][1]);if(a&&b){g.save();g.strokeStyle='#fff';g.lineWidth=Math.max(5,rr.rx*1.7);g.lineCap='round';g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke();g.restore();return;}}g.fillStyle='#fff';g.beginPath();g.ellipse(rr.cx,rr.cy,Math.max(4,rr.rx*1.12),Math.max(4,rr.ry*1.12),0,0,Math.PI*2);g.fill();}
function semanticMask(o,keys,f){var sig=[o.id,o.meshRev||0,o.maskRev||0,f,keys.join(',')].join('|');if(maskCache.has(sig))return maskCache.get(sig);var c=document.createElement('canvas');c.width=o.width;c.height=o.height;var g=c.getContext('2d');keys.forEach(function(k){paintRegion(g,o,k);});if(f>0){var b=document.createElement('canvas');b.width=o.width;b.height=o.height;var bg=b.getContext('2d');bg.filter='blur('+Math.min(20,f)+'px)';bg.drawImage(c,0,0);c=b;}maskCache.set(sig,c);if(maskCache.size>64)maskCache.delete(maskCache.keys().next().value);return c;}
function rendered(o){var base=litLayerImage(o);return o.mesh&&o.mesh.points&&o.mesh.points.length?meshWarpCanvas(o,base):base;}
function isolate(o,keys,f){var c=document.createElement('canvas');c.width=o.width;c.height=o.height;var g=c.getContext('2d');g.drawImage(rendered(o),0,0);g.globalCompositeOperation='destination-in';g.drawImage(semanticMask(o,keys,f),0,0);return c;}
function exclude(o){var ex=(o.semanticDepthExclusions||[]).filter(function(x){return x.keys&&x.keys.length;});if(!ex.length)return rendered(o);var c=document.createElement('canvas');c.width=o.width;c.height=o.height;var g=c.getContext('2d');g.drawImage(rendered(o),0,0);g.globalCompositeOperation='destination-out';ex.forEach(function(x){g.drawImage(semanticMask(o,x.keys,x.feather||7),0,0);});return c;}
function drawPrepared(o,img,shadow){if(shadow)drawContactShadow(o);ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.scale(o.scaleX||1,o.scaleY||1);ctx.globalAlpha=o.opacity==null?1:o.opacity;if(o.shadow>0){ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=o.shadow;ctx.shadowOffsetX=o.shadow*.15;ctx.shadowOffsetY=o.shadow*.35;}drawBentImage(ctx,img,o.width,o.height,o.bend||0);ctx.restore();}
var drawLayer0=drawLayer;drawLayer=function(l,s){if(l&&l.semanticDepthPass){if(!l.visible)return;var o=state.layers.find(function(x){return x.id===l.semanticOwnerId;});if(o&&o.visible)drawPrepared(o,isolate(o,l.semanticRegionKeys||[],l.semanticFeather||7),false);return;}if(l&&l.kind==='character'&&l.semanticDepthExclusions&&l.semanticDepthExclusions.length){drawPrepared(l,exclude(l),true);return;}drawLayer0(l,s);};
function tiny(){var c=document.createElement('canvas');c.width=2;c.height=2;return c.toDataURL('image/png');}
async function addDepth(side,keys,t){var o=ownerFor(selected());t=t||target();if(!o||o.kind!=='character'||!t){say(msg('চরিত্র ও সামনে/পেছনের টার্গেট বাছুন।','Choose a character and occlusion target.'),true);return null;}keys=(keys||[]).filter(function(k){return regs(o)&&regs(o)[k];});if(!keys.length){say(msg('একটি শরীরের অংশ বাছুন।','Choose a body region.'),true);return null;}var src=tiny(),im=await imageFromDataURL(src);var p=Object.assign({id:uid('depth'),kind:'part',name:'Depth '+side+': '+keys.join(' + '),src:src,baseSrc:src,width:o.width,height:o.height,image:im},layerDefaults(),{ownerId:o.id,partRole:'semantic-depth',semanticDepthPass:true,semanticOwnerId:o.id,semanticTargetId:t.id,semanticRegionKeys:keys,semanticSide:side,semanticFeather:feather()});var i=state.layers.findIndex(function(x){return x.id===t.id;});state.layers.splice(side==='front'?i+1:i,0,p);if(side==='behind'){o.semanticDepthExclusions=o.semanticDepthExclusions||[];o.semanticDepthExclusions.push({passId:p.id,targetId:t.id,keys:keys.slice(),feather:p.semanticFeather});}state.selectedId=p.id;commit('v0.11 semantic depth '+side);return p;}
function clearDepth(){var o=ownerFor(selected());if(!o)return;var ids=new Set(state.layers.filter(function(x){return x.semanticDepthPass&&x.semanticOwnerId===o.id;}).map(function(x){return x.id;}));state.layers=state.layers.filter(function(x){return !ids.has(x.id);});o.semanticDepthExclusions=(o.semanticDepthExclusions||[]).filter(function(x){return !ids.has(x.passId);});state.selectedId=o.id;commit('clear semantic depth');say(msg('Depth split পরিষ্কার হয়েছে।','Semantic depth splits cleared.'));}
async function cover(keys){var o=ownerFor(selected()),t=target();if(!o||!t)return;moveRelative(o,t,false);await addDepth('front',keys,t);}
if($('#depthFrontBtn'))$('#depthFrontBtn').addEventListener('click',function(){addDepth('front',depthKeys());});
if($('#depthBehindBtn'))$('#depthBehindBtn').addEventListener('click',function(){addDepth('behind',depthKeys());});
if($('#depthFaceOnlyBtn'))$('#depthFaceOnlyBtn').addEventListener('click',function(){cover(['head']);});
if($('#depthFaceHandsBtn'))$('#depthFaceHandsBtn').addEventListener('click',function(){cover(['head','lHand','rHand']);});
if($('#depthClearBtn'))$('#depthClearBtn').addEventListener('click',clearDepth);
if($('#depthFeatherCtrl'))$('#depthFeatherCtrl').addEventListener('input',function(){if($('#depthFeatherOut'))$('#depthFeatherOut').textContent=$('#depthFeatherCtrl').value+'px';});
var limb={lUpperArm:[11,13,15],lForearm:[11,13,15],lHand:[11,13,15],rUpperArm:[12,14,16],rForearm:[12,14,16],rHand:[12,14,16],lThigh:[23,25,27],lLowerLeg:[23,25,27],lFoot:[23,25,27],rThigh:[24,26,28],rLowerLeg:[24,26,28],rFoot:[24,26,28]};
function cross(a,b,c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);}
function solve(root,mid,end,t,l1,l2,sgn){var vx=t.x-root.x,vy=t.y-root.y,raw=Math.hypot(vx,vy)||.001,dd=clamp(raw,Math.abs(l1-l2)+.001,l1+l2-.001),base=Math.atan2(vy,vx),ca=clamp((l1*l1+dd*dd-l2*l2)/(2*l1*dd),-1,1),a=Math.acos(ca),ang=base+sgn*a,ratio=dd/raw;return{m:{x:root.x+Math.cos(ang)*l1,y:root.y+Math.sin(ang)*l1},e:{x:root.x+vx*ratio,y:root.y+vy*ratio},reachable:raw<=l1+l2+.5};}
function setPose(l,i,p){var q=pose(l)&&pose(l)[i];if(q){q.x=clamp(p.x/l.width,0,1);q.y=clamp(p.y/l.height,0,1);}}
function moveIK(o,spec,t){var r=pt(o,spec[0]),m=pt(o,spec[1]),e=pt(o,spec[2]);if(!r||!m||!e)return false;mesh(o);var l1=d(r,m),l2=d(m,e),z=solve(r,m,e,t,l1,l2,cross(r,e,m)>=0?1:-1),rad=Math.max(28,(l1+l2)*.34);applySoftMeshDelta(o,m,z.m.x-m.x,z.m.y-m.y,rad,.8);applySoftMeshDelta(o,e,z.e.x-e.x,z.e.y-e.y,rad*.9,.92);setPose(o,spec[1],z.m);setPose(o,spec[2],z.e);invalidate(o);return z.reachable;}
function contactTarget(){return state.layers.find(function(x){return x.id===(($('#semanticContactTarget')&&$('#semanticContactTarget').value)||'');});}
function targetPoint(t,k){var rr=regs(t)&&regs(t)[k];return rr?{x:rr.cx,y:rr.cy}:{x:t.width/2,y:t.height/2};}
function fillContacts(){var s=$('#semanticContactTarget');if(!s)return;var cur=s.value,o=ownerFor(selected());s.innerHTML='<option value="">Choose character</option>';chars().filter(function(x){return !o||x.id!==o.id;}).forEach(function(x){var op=document.createElement('option');op.value=x.id;op.textContent=x.name;s.append(op);});if(Array.from(s.options).some(function(x){return x.value===cur;}))s.value=cur;}
function bindContact(){var o=ownerFor(selected()),t=contactTarget(),spec=limb[rkey()];if(!o||!t||!pose(o)||!spec){say(msg('হাত/পায়ের limb বাছুন, target দিন, তারপর Analyze চালান।','Choose a hand/foot limb, target, and run Analyze first.'),true);return;}var tr=($('#semanticTargetRegion')&&$('#semanticTargetRegion').value)||'abdomen',lp=targetPoint(t,tr),world=localToWorld(t,lp),desired=worldToLocal(o,world);o.semanticContacts=o.semanticContacts||[];o.semanticContacts=o.semanticContacts.filter(function(c){return c.end!==spec[2];});o.semanticContacts.push({id:uid('contact'),end:spec[2],targetId:t.id,targetRegion:tr});var ok=moveIK(o,spec,desired);commit('v0.11 semantic contact');say(ok?msg('Contact বসেছে। Target নড়লে limb follow করবে।','Contact pinned. The limb will follow the target.'):msg('Target limb reach-এর বাইরে। চরিত্র দুটো কাছে আনুন।','Target is outside limb reach. Move the characters closer.'));}
function releaseContact(){var o=ownerFor(selected()),spec=limb[rkey()];if(!o||!o.semanticContacts)return;o.semanticContacts=spec?o.semanticContacts.filter(function(c){return c.end!==spec[2];}):[];commit('release semantic contact');}
if($('#semanticContactBtn'))$('#semanticContactBtn').addEventListener('click',bindContact);if($('#semanticReleaseBtn'))$('#semanticReleaseBtn').addEventListener('click',releaseContact);
function updateContacts(){chars().forEach(function(o){(o.semanticContacts||[]).forEach(function(c){var t=state.layers.find(function(x){return x.id===c.targetId;}),spec=Object.values(limb).find(function(s){return s[2]===c.end;});if(!t||!spec||!pose(o))return;var world=localToWorld(t,targetPoint(t,c.targetRegion)),desired=worldToLocal(o,world),cur=pt(o,spec[2]);if(cur&&d(cur,desired)>.8)moveIK(o,spec,desired);});});}
var draw0=draw;draw=function(){updateContacts();draw0();};
var render0=renderUI;renderUI=function(){render0();fillContacts();if($('#depthFeatherOut'))$('#depthFeatherOut').textContent=feather()+'px';var o=ownerFor(selected()),n=o&&o.semanticContacts?o.semanticContacts.length:0;if($('#semanticContactStatus'))$('#semanticContactStatus').textContent=n?(n+' contact(s) active'):msg('কোনো semantic contact নেই','No semantic contact');if(window.PoseForgeI18n&&window.PoseForgeI18n.localizeTree)window.PoseForgeI18n.localizeTree(document.body);};
['#occlusionFaceBtn','#occlusionRegionFrontBtn'].forEach(function(id){var el=$(id);if(el)el.style.display='none';});
window.PoseForgeV011={addDepth:addDepth,clearDepth:clearDepth,depthKeys:depthKeys,bindContact:bindContact,releaseContact:releaseContact};
})();