/* PoseForge 2D v0.11 semantic depth + limb-chain contact */
(function(){
'use strict';
var lang=function(){return window.PoseForgeI18n&&window.PoseForgeI18n.lang?window.PoseForgeI18n.lang():'bn';};
var msg=function(bn,en){return lang()==='bn'?bn:en;};
var ownerFor=function(l){return typeof personOwner==='function'?personOwner(l):(l&&l.kind==='character'?l:state.layers.find(function(x){return x.id===(l&&l.ownerId);})||l);};
var pose=function(l){return l&&l.aiAnalysis&&l.aiAnalysis.poses&&l.aiAnalysis.poses[0]||null;};
var pt=function(l,i){var p=pose(l)&&pose(l)[i];return p?{x:p.x*l.width,y:p.y*l.height}:null;};
var d=function(a,b){return a&&b?Math.hypot(a.x-b.x,a.y-b.y):0;};
var regs=function(l){return window.PoseForgeBodyRegions&&window.PoseForgeBodyRegions.bodyRegions?window.PoseForgeBodyRegions.bodyRegions(l):null;};
var rkey=function(){return ($('#easyRegionSelect')&&$('#easyRegionSelect').value)||'whole';};
var target=function(){return state.layers.find(function(x){return x.id===(($('#occlusionTarget')&&$('#occlusionTarget').value)||'');});};
var feather=function(){return Number(($('#depthFeatherCtrl')&&$('#depthFeatherCtrl').value)||7);};
var maskCache=new Map();
function commit(s){pushHistory(s);renderUI();draw();autoSave();}
function mesh(l){if(!l.mesh)createMeshForLayer(l,9);return l.mesh;}
function invalidate(l){l.meshRev=(l.meshRev||0)+1;if(typeof meshRenderCache!=='undefined')meshRenderCache.delete(l);}
function family(o){return [o].concat(state.layers.filter(function(x){return x.ownerId===o.id&&!x.semanticDepthPass;}));}
function moveRelative(o,t,front){if(!o||!t||o.id===t.id)return false;var f=family(o),ids=new Set(f.map(function(x){return x.id;}));state.layers=state.layers.filter(function(x){return !ids.has(x.id);});var i=state.layers.findIndex(function(x){return x.id===t.id;});if(i<0){state.layers.push.apply(state.layers,f);return false;}state.layers.splice.apply(state.layers,[front?i+1:i,0].concat(f));return true;}
var outward={lUpperArm:['lUpperArm','lForearm','lHand'],rUpperArm:['rUpperArm','rForearm','rHand'],lForearm:['lForearm','lHand'],rForearm:['rForearm','rHand'],lThigh:['lThigh','lLowerLeg','lFoot'],rThigh:['rThigh','rLowerLeg','rFoot'],lLowerLeg:['lLowerLeg','lFoot'],rLowerLeg:['rLowerLeg','rFoot']};
var wholeLimb={lUpperArm:['lUpperArm','lForearm','lHand'],lForearm:['lUpperArm','lForearm','lHand'],lHand:['lUpperArm','lForearm','lHand'],rUpperArm:['rUpperArm','rForearm','rHand'],rForearm:['rUpperArm','rForearm','rHand'],rHand:['rUpperArm','rForearm','rHand'],lThigh:['lThigh','lLowerLeg','lFoot'],lLowerLeg:['lThigh','lLowerLeg','lFoot'],lFoot:['lThigh','lLowerLeg','lFoot'],rThigh:['rThigh','rLowerLeg','rFoot'],rLowerLeg:['rThigh','rLowerLeg','rFoot'],rFoot:['rThigh','rLowerLeg','rFoot']};
function depthKeys(){var k=rkey(),m=($('#depthChainMode')&&$('#depthChainMode').value)||'region';if(k==='whole')return[];if(m==='outward'&&outward[k])return outward[k].slice();if(m==='limb'&&wholeLimb[k])return wholeLimb[k].slice();return[k];}
var seg={lUpperArm:[11,13],rUpperArm:[12,14],lForearm:[13,15],rForearm:[14,16],lThigh:[23,25],rThigh:[24,26],lLowerLeg:[25,27],rLowerLeg:[26,28]};
function paintRegion(g,o,k){var rr=regs(o)&&regs(o)[k];if(!rr)return;if(seg[k]){var a=pt(o,seg[k][0]),b=pt(o,seg[k][1]);if(a&&b){g.save();g.strokeStyle='#fff';g.lineWidth=Math.max(5,rr.rx*1.7);g.lineCap='round';g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke();g.restore();return;}}g.fillStyle='#fff';g.beginPath();g.ellipse(rr.cx,rr.cy,Math.max(4,rr.rx*1.12),Math.max(4,rr.ry*1.12),0,0,Math.PI*2);g.fill();}
function semanticMask(o,keys,f){var sig=[o.id,o.meshRev||0,o.maskRev||0,f,keys.join(',')].join('|');if(maskCache.has(sig))return maskCache.get(sig);var c=document.createElement('canvas');c.width=o.width;c.height=o.height;var g=c.getContext('2d');keys.forEach(function(k){paintRegion(g,o,k);});if(f>0){var b=document.createElement('canvas');b.width=o.width;b.height=o.height;var bg=b.getContext('2d');bg.filter='blur('+Math.min(20,f)+'px)';bg.drawImage(c,0,0);c=b;}maskCache.set(sig,c);if(maskCache.size>64)maskCache.delete(maskCache.keys().next().value);return c;}
function rendered(o){var base=litLayerImage(o);return o.mesh&&o.mesh.points&&o.mesh.points.length?meshWarpCanvas(o,base):base;}
function isolate(o,keys,f){var c=document.createElement('canvas');c.width=o.width;c.height=o.height;var g=c.getContext('2d');g.drawImage(rendered(o),0,0);g.globalCompositeOperation='destination-in';g.drawImage(semanticMask(o,keys,f),0,0);return c;}
function exclude(o){var ex=(o.semanticDepthExclusions||[]).filter(function(x){return x.keys&&x.keys.length&&state.layers.some(function(l){return l.id===x.passId;});});if(!ex.length)return rendered(o);var c=document.createElement('canvas');c.width=o.width;c.height=o.height;var g=c.getContext('2d');g.drawImage(rendered(o),0,0);g.globalCompositeOperation='destination-out';ex.forEach(function(x){g.drawImage(semanticMask(o,x.keys,x.feather||7),0,0);});return c;}
function drawPrepared(o,img,shadow){if(shadow)drawContactShadow(o);ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.scale(o.scaleX||1,o.scaleY||1);ctx.globalAlpha=o.opacity==null?1:o.opacity;if(o.shadow>0){ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=o.shadow;ctx.shadowOffsetX=o.shadow*.15;ctx.shadowOffsetY=o.shadow*.35;}drawBentImage(ctx,img,o.width,o.height,o.bend||0);ctx.restore();}
var drawLayer0=drawLayer;drawLayer=function(l,s){if(l&&l.semanticDepthPass){if(!l.visible)return;var o=state.layers.find(function(x){return x.id===l.semanticOwnerId;});if(o&&o.visible)drawPrepared(o,isolate(o,l.semanticRegionKeys||[],l.semanticFeather||7),false);return;}if(l&&l.kind==='character'&&l.semanticDepthExclusions&&l.semanticDepthExclusions.length){drawPrepared(l,exclude(l),true);return;}drawLayer0(l,s);};
function tiny(){var c=document.createElement('canvas');c.width=2;c.height=2;return c.toDataURL('image/png');}
async function addDepth(side,keys,t){var o=ownerFor(selected());t=t||target();if(!o||o.kind!=='character'||!t){say(msg('চরিত্র ও সামনে/পেছনের টার্গেট বাছুন।','Choose a character and occlusion target.'),true);return null;}keys=(keys||[]).filter(function(k){return regs(o)&&regs(o)[k];});if(!keys.length){say(msg('একটি শরীরের অংশ বাছুন।','Choose a body region.'),true);return null;}var src=tiny(),im=await imageFromDataURL(src);var p=Object.assign({id:uid('depth'),kind:'part',name:'Depth '+side+': '+keys.join(' + '),src:src,baseSrc:src,width:o.width,height:o.height,image:im},layerDefaults(),{ownerId:o.id,partRole:'semantic-depth',semanticDepthPass:true,semanticOwnerId:o.id,semanticTargetId:t.id,semanticRegionKeys:keys,semanticSide:side,semanticFeather:feather()});var i=state.layers.findIndex(function(x){return x.id===t.id;});state.layers.splice(side==='front'?i+1:i,0,p);if(side==='behind'){o.semanticDepthExclusions=o.semanticDepthExclusions||[];o.semanticDepthExclusions.push({passId:p.id,targetId:t.id,keys:keys.slice(),feather:p.semanticFeather});}state.selectedId=p.id;commit('v0.11 semantic depth '+side);return p;}
function clearDepth(){var o=ownerFor(selected());if(!o)return;var ids=new Set(state.layers.filter(function(x){return x.semanticDepthPass&&x.semanticOwnerId===o.id;}).map(function(x){return x.id;}));state.layers=state.layers.filter(function(x){return !ids.has(x.id);});o.semanticDepthExclusions=(o.semanticDepthExclusions||[]).filter(function(x){return !ids.has(x.passId);});state.selectedId=o.id;commit('clear semantic depth');say(msg('Depth split পরিষ্কার হয়েছে।','Semantic depth splits cleared.'));}
async function cover(keys){var o=ownerFor(selected()),t=target();if(!o||!t)return;moveRelative(o,t,false);await addDepth('front',keys,t);}
if($('#depthFrontBtn'))$('#depthFrontBtn').addEventListener('click',function(){addDepth('front',depthKeys());});
if($('#depthBehindBtn'))$('#depthBehindBtn').addEventListener('click',function(){addDepth('behind',depthKeys());});
if($('#depthFaceOnlyBtn'))$('#depthFaceOnlyBtn').addEventListener('click',function(){cover(['head']);});
if($('#depthFaceHandsBtn'))$('#depthFaceHandsBtn').addEventListener('click',function(){cover(['head','lHand','rHand']);});
if($('#depthClearBtn'))$('#depthClearBtn').addEventListener('click',clearDepth);
if($('#depthFeatherCtrl'))$('#depthFeatherCtrl').addEventListener('input',function(){if($('#depthFeatherOut'))$('#depthFeatherOut').textContent=$('#depthFeatherCtrl').value+'px';});
var limb={lUpperArm:[11,13,15],lForearm:[11,13,15],lHand:[11,13,15],rUpperArm:[12,14,16],rForearm:[12,14,16],rHand:[12,14,16],lThigh:[23,25,27],lLowerLeg:[23,25,27],lFoot:[23,25,27],rThigh:[24,26,28],rLowerLeg:[24,26,28],rFoot:[24,26,28]};
function cross(a,b,c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);}
function solve(root,mid,end,t,l1,l2,sgn){var vx=t.x-root.x,vy=t.y-root.y,raw=Math.hypot(vx,vy)||.001,dd=clamp(raw,Math.abs(l1-l2)+.001,l1+l2-.001),base=Math.atan2(vy,vx),ca=clamp((l1*l1+dd*dd-l2*l2)/(2*l1*dd),-1,1),a=Math.acos(ca),ang=base+sgn*a,ratio=dd/raw;return{m:{x:root.x+Math.cos(ang)*l1,y:root.y+Math.sin(ang)*l1},e:{x:root.x+vx*ratio,y:root.y+vy*ratio},reachable:raw<=l1+l2+.5};}
function setPose(l,i,p){var q=pose(l)&&pose(l)[i];if(q){q.x=clamp(p.x/l.width,0,1);q.y=clamp(p.y/l.height,0,1);}}
function moveIK(o,spec,t){var r=pt(o,spec[0]),m=pt(o,spec[1]),e=pt(o,spec[2]);if(!r||!m||!e)return false;mesh(o);var l1=d(r,m),l2=d(m,e),z=solve(r,m,e,t,l1,l2,cross(r,e,m)>=0?1:-1),rad=Math.max(28,(l1+l2)*.34);applySoftMeshDelta(o,m,z.m.x-m.x,z.m.y-m.y,rad,.8);applySoftMeshDelta(o,e,z.e.x-e.x,z.e.y-e.y,rad*.9,.92);setPose(o,spec[1],z.m);setPose(o,spec[2],z.e);invalidate(o);return z.reachable;}
function contactTarget(){return state.layers.find(function(x){return x.id===(($('#semanticContactTarget')&&$('#semanticContactTarget').value)||'');});}
function targetPoint(t,k){var rr=regs(t)&&regs(t)[k];return rr?{x:rr.cx,y:rr.cy}:{x:t.width/2,y:t.height/2};}
function fillContacts(){var s=$('#semanticContactTarget');if(!s)return;var cur=s.value,o=ownerFor(selected());s.innerHTML='<option value="">Choose character</option>';chars().filter(function(x){return !o||x.id!==o.id;}).forEach(function(x){var op=document.createElement('option');op.value=x.id;op.textContent=x.name;s.append(op);});if(Array.from(s.options).some(function(x){return x.value===cur;}))s.value=cur;}
function bindContact(){var o=ownerFor(selected()),t=contactTarget(),spec=limb[rkey()];if(!o||!t||!pose(o)||!spec){say(msg('হাত/পায়ের limb বাছুন, target দিন, তারপর Analyze চালান।','Choose a hand/foot limb, target, and run Analyze first.'),true);return;}var tr=($('#semanticTargetRegion')&&$('#semanticTargetRegion').value)||'abdomen',lp=targetPoint(t,tr),world=localToWorld(t,lp),desired=worldToLocal(o,world);o.semanticContacts=o.semanticContacts||[];o.semanticContacts=o.semanticContacts.filter(function(c){return c.end!==spec[2];});o.semanticContacts.push({id:uid('contact'),end:spec[2],targetId:t.id,targetRegion:tr});var ok=moveIK(o,spec,desired);commit('v0.11 semantic contact');say(ok?msg('Contact বসেছে। Target নড়লে limb follow করবে।','Contact pinned. The limb will follow the target.'):msg('Target limb reach-এর বাইরে। চরিত্র দুটো কাছে আনুন।','Target is outside limb reach. Move the characters closer.'));}
function releaseContact(){var o=ownerFor(selected()),spec=limb[rkey()];if(!o||!o.semanticContacts)return;o.semanticContacts=spec?o.semanticContacts.filter(function(c){return c.end!==spec[2];}):[];commit('release semantic contact');}
if($('#semanticContactBtn'))$('#semanticContactBtn').addEventListener('click',bindContact);if($('#semanticReleaseBtn'))$('#semanticReleaseBtn').addEventListener('click',releaseContact);
function updateContacts(){chars().forEach(function(o){(o.semanticContacts||[]).forEach(function(c){var t=state.layers.find(function(x){return x.id===c.targetId;}),spec=Object.values(limb).find(function(s){return s[2]===c.end;});if(!t||!spec||!pose(o))return;var world=localToWorld(t,targetPoint(t,c.targetRegion)),desired=worldToLocal(o,world),cur=pt(o,spec[2]);if(cur&&d(cur,desired)>.8)moveIK(o,spec,desired);});});}
var draw0=draw;draw=function(){updateContacts();draw0();};
var render0=renderUI;renderUI=function(){render0();fillContacts();if($('#depthFeatherOut'))$('#depthFeatherOut').textContent=feather()+'px';var o=ownerFor(selected()),n=o&&o.semanticContacts?o.semanticContacts.length:0;if($('#semanticContactStatus'))$('#semanticContactStatus').textContent=n?(n+' contact(s) active'):msg('কোনো semantic contact নেই','No semantic contact');if(window.PoseForgeI18n&&window.PoseForgeI18n.localizeTree)window.PoseForgeI18n.localizeTree(document.body);};
['#occlusionFaceBtn','#occlusionRegionFrontBtn'].forEach(function(id){var el=$(id);if(el)el.style.display='none';});
window.PoseForgeV011={addDepth:addDepth,clearDepth:clearDepth,depthKeys:depthKeys,bindContact:bindContact,releaseContact:releaseContact};
})();

/* PoseForge 2D v0.12 general interaction graph */
(function(){
'use strict';
var bn=function(b,e){return window.PoseForgeI18n&&PoseForgeI18n.lang&&PoseForgeI18n.lang()==='bn'?b:e};
var own=function(l){return typeof personOwner==='function'?personOwner(l):(l&&l.kind==='character'?l:state.layers.find(function(x){return x.id===(l&&l.ownerId)})||l)};
var actor=function(){return own(selected())}, people=function(){return typeof chars==='function'?chars():state.layers.filter(function(x){return x.kind==='character'})};
var pose0=function(l){return l&&l.aiAnalysis&&l.aiAnalysis.poses&&l.aiAnalysis.poses[0]||null}, pp=function(l,i){var p=pose0(l)&&pose0(l)[i];return p?{x:p.x*l.width,y:p.y*l.height}:null};
var regions=function(l){return window.PoseForgeBodyRegions&&PoseForgeBodyRegions.bodyRegions?PoseForgeBodyRegions.bodyRegions(l):null}, dd=function(a,b){return a&&b?Math.hypot(a.x-b.x,a.y-b.y):0};
var specs={lHand:[11,13,15],rHand:[12,14,16],lFoot:[23,25,27],rFoot:[24,26,28],lElbow:[11,13,15],rElbow:[12,14,16],lKnee:[23,25,27],rKnee:[24,26,28]};
var mids={lElbow:1,rElbow:1,lKnee:1,rKnee:1}, joints={lShoulder:11,rShoulder:12,lElbow:13,rElbow:14,lHand:15,rHand:16,lHip:23,rHip:24,lKnee:25,rKnee:26,lFoot:27,rFoot:28};
var depthKeys={lHand:['lUpperArm','lForearm','lHand'],rHand:['rUpperArm','rForearm','rHand'],lFoot:['lThigh','lLowerLeg','lFoot'],rFoot:['rThigh','rLowerLeg','rFoot'],lElbow:['lUpperArm','lForearm'],rElbow:['rUpperArm','rForearm'],lKnee:['lThigh','lLowerLeg'],rKnee:['rThigh','rLowerLeg']};
var solving=false,picking=false,health={ok:0,limit:0,bad:0};
function commit(x){pushHistory(x);renderUI();draw();autoSave()}
function mesh(a){if(!a.mesh)createMeshForLayer(a,9);return a.mesh}
function invalid(a){a.meshRev=(a.meshRev||0)+1;if(typeof meshRenderCache!=='undefined')meshRenderCache.delete(a)}
function fam(a){return[a].concat(state.layers.filter(function(x){return x.ownerId===a.id&&!x.semanticDepthPass}))}
function move(a,x,y){if(typeof wholePersonMove==='function')wholePersonMove(a,x,y);else fam(a).forEach(function(l){l.x+=x;l.y+=y})}
function setp(a,i,p){var q=pose0(a)&&pose0(a)[i];if(q){q.x=Math.max(0,Math.min(1,p.x/a.width));q.y=Math.max(0,Math.min(1,p.y/a.height))}}
function rp(t,k){if(joints[k]!=null){var j=pp(t,joints[k]);if(j)return j}var r=regions(t)&&regions(t)[k];return r?{x:r.cx,y:r.cy}:{x:t.width/2,y:t.height/2}}
function sp(a,k){var s=specs[k];if(s)return pp(a,mids[k]?s[1]:s[2]);return rp(a,k)}
function solve2(r,m,e,t,l1,l2,sgn){var vx=t.x-r.x,vy=t.y-r.y,raw=Math.hypot(vx,vy)||.001,d=Math.max(Math.abs(l1-l2)+.001,Math.min(l1+l2-.001,raw)),ba=Math.atan2(vy,vx),ca=Math.max(-1,Math.min(1,(l1*l1+d*d-l2*l2)/(2*l1*d))),an=ba+(sgn||1)*Math.acos(ca),q=d/raw;return{m:{x:r.x+Math.cos(an)*l1,y:r.y+Math.sin(an)*l1},e:{x:r.x+vx*q,y:r.y+vy*q},ok:raw<=l1+l2+.5}}
function cross(a,b,c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x)}
function target(a,c){var t=state.layers.find(function(x){return x.id===c.targetId})||a,p=rp(t,c.targetKey);if(!p)return null;return{t:t,w:localToWorld(t,{x:p.x+(c.ox||0),y:p.y+(c.oy||0)})}}
function solveContact(a,c){
 if(c.on===false)return'ok';var tw=target(a,c),s=specs[c.sourceKey];if(!tw)return'bad';
 if(!s){if(c.targetId===a.id)return'bad';var p=sp(a,c.sourceKey);if(!p)return'bad';var w=localToWorld(a,p),k=Math.max(.15,Math.min(1,(c.strength||100)/100));move(a,(tw.w.x-w.x)*k,(tw.w.y-w.y)*k);return'ok'}
 var r=pp(a,s[0]),m=pp(a,s[1]),e=pp(a,s[2]);if(!r||!m||!e)return'bad';mesh(a);var t=worldToLocal(a,tw.w);
 if(c.autoReach&&c.targetId!==a.id&&!mids[c.sourceKey]){var reach=dd(r,m)+dd(m,e),raw=dd(r,t);if(raw>reach*.98){var ex=raw-reach*.92,ux=(t.x-r.x)/(raw||1),uy=(t.y-r.y)/(raw||1),z0=localToWorld(a,{x:0,y:0}),z1=localToWorld(a,{x:ux*ex,y:uy*ex});move(a,z1.x-z0.x,z1.y-z0.y);r=pp(a,s[0]);m=pp(a,s[1]);e=pp(a,s[2]);t=worldToLocal(a,tw.w)}}
 var k=Math.max(.15,Math.min(1,(c.strength||100)/100)),rad=Math.max(28,(dd(r,m)+dd(m,e))*.34);
 if(mids[c.sourceKey]){var l=dd(r,m),vx=t.x-r.x,vy=t.y-r.y,raw=Math.hypot(vx,vy)||.001,g={x:r.x+vx/raw*l,y:r.y+vy/raw*l},nm={x:m.x+(g.x-m.x)*k,y:m.y+(g.y-m.y)*k},dx=nm.x-m.x,dy=nm.y-m.y,ne={x:e.x+dx,y:e.y+dy};applySoftMeshDelta(a,m,dx,dy,rad,.82);applySoftMeshDelta(a,e,dx,dy,rad*.9,.68);setp(a,s[1],nm);setp(a,s[2],ne);invalid(a);return Math.abs(raw-l)<l*.3?'ok':'limit'}
 var z=solve2(r,m,e,t,dd(r,m),dd(m,e),cross(r,e,m)>=0?1:-1),nm={x:m.x+(z.m.x-m.x)*k,y:m.y+(z.m.y-m.y)*k},ne={x:e.x+(z.e.x-e.x)*k,y:e.y+(z.e.y-e.y)*k};applySoftMeshDelta(a,m,nm.x-m.x,nm.y-m.y,rad,.8);applySoftMeshDelta(a,e,ne.x-e.x,ne.y-e.y,rad*.92,.94);setp(a,s[1],nm);setp(a,s[2],ne);invalid(a);return z.ok?'ok':'limit'
}
function solveAll(){if(solving)return;solving=true;var h={ok:0,limit:0,bad:0};try{for(var z=0;z<3;z++)people().forEach(function(a){(a.interactionContacts||[]).filter(function(c){return c.live!==false}).forEach(function(c){var r=solveContact(a,c);if(z===2)h[r]=(h[r]||0)+1})})}finally{solving=false;health=h}}
function v(id,d){var e=$(id);return e&&e.value!=null?e.value:d}function n(id,d){return Number(v(id,d))}function ck(id,d){var e=$(id);return e?!!e.checked:!!d}
function targetChar(a){var id=v('#interactionTarget','self');return id==='self'?a:state.layers.find(function(x){return x.id===id})}
function newid(){return typeof uid==='function'?uid('ix'):('ix_'+Date.now()+'_'+Math.random().toString(36).slice(2))}
function rmDepth(a,c){if(!c.depthPassId)return;var id=c.depthPassId;state.layers=state.layers.filter(function(x){return x.id!==id});a.semanticDepthExclusions=(a.semanticDepthExclusions||[]).filter(function(x){return x.passId!==id});c.depthPassId=null}
async function depth(a,c,t){if(!window.PoseForgeV011||!PoseForgeV011.addDepth||c.depth==='keep'||t===a||!depthKeys[c.sourceKey])return;var old=state.selectedId;state.selectedId=a.id;try{var p=await PoseForgeV011.addDepth(c.depth,depthKeys[c.sourceKey],t);if(p)c.depthPassId=p.id}catch(e){}state.selectedId=old&&state.layers.some(function(x){return x.id===old})?old:a.id}
async function put(a,c,useDepth){a.interactionContacts=a.interactionContacts||[];a.interactionContacts.filter(function(x){return x.sourceKey===c.sourceKey}).forEach(function(x){rmDepth(a,x)});a.interactionContacts=a.interactionContacts.filter(function(x){return x.sourceKey!==c.sourceKey});a.interactionContacts.push(c);solveContact(a,c);if(useDepth)await depth(a,c,state.layers.find(function(x){return x.id===c.targetId}));return c}
async function add(){
 var a=actor();if(!a||a.kind!=='character'){say(bn('আগে একটি চরিত্র বাছুন।','Select a character first.'),true);return}var t=targetChar(a);if(!t)return;var sk=v('#interactionSource','rHand');
 if(t===a&&!specs[sk]){say(bn('Self-contact-এর source হিসেবে হাত, পা, কনুই বা হাঁটু বাছুন।','For self-contact choose a hand, foot, elbow or knee.'),true);return}if(specs[sk]&&!pose0(a)){say(bn('এই contact-এর আগে Analyze selected চালান।','Run Analyze selected first.'),true);return}
 var c={id:newid(),sourceKey:sk,targetId:t.id,targetKey:v('#interactionTargetRegion','chest'),ox:n('#interactionOffsetX',0),oy:n('#interactionOffsetY',0),strength:n('#interactionStrength',100),autoReach:ck('#interactionAutoReach',true),live:ck('#interactionLive',true),depth:v('#interactionDepth','keep'),on:true};await put(a,c,true);commit('v0.12 interaction contact')
}
function clear(){var a=actor();if(!a)return;(a.interactionContacts||[]).forEach(function(c){rmDepth(a,c)});a.interactionContacts=[];commit('clear interaction')}
function del(id){var a=actor(),c=a&&(a.interactionContacts||[]).find(function(x){return x.id===id});if(c)rmDepth(a,c);a.interactionContacts=(a.interactionContacts||[]).filter(function(x){return x.id!==id});commit('remove interaction')}
function tog(id){var a=actor(),c=a&&(a.interactionContacts||[]).find(function(x){return x.id===id});if(c){c.on=c.on===false;commit('toggle interaction')}}
function faceNo(a,t){var aw=localToWorld(a,{x:a.width*.5,y:a.height*.45}),tw=localToWorld(t,{x:t.width*.5,y:t.height*.45}),m=Math.max(.05,Math.abs(a.scaleX||1));a.scaleX=tw.x>=aw.x?m:-m}
function face(){var a=actor(),t=targetChar(a);if(a&&t&&a!==t){faceNo(a,t);commit('face target')}}
function distNo(a,t,g){var ac=localToWorld(a,{x:a.width*.5,y:a.height*.5}),tc=localToWorld(t,{x:t.width*.5,y:t.height*.5}),x=ac.x-tc.x,y=ac.y-tc.y,r=Math.hypot(x,y)||1;move(a,tc.x+x/r*g-ac.x,tc.y+y/r*g-ac.y)}
function near(){var a=actor(),t=targetChar(a);if(a&&t&&a!==t){distNo(a,t,n('#interactionDistance',160));commit('arrange distance')}}
function rel(front){var a=actor(),t=targetChar(a);if(!a||!t||a===t)return;var f=fam(a),ids=new Set(f.map(function(x){return x.id}));state.layers=state.layers.filter(function(x){return!ids.has(x.id)});var i=state.layers.findIndex(function(x){return x.id===t.id});state.layers.splice.apply(state.layers,[front?i+1:i,0].concat(f));commit(front?'front':'behind')}
function cc(a,t,s,k,o){o=o||{};return{id:newid(),sourceKey:s,targetId:t.id,targetKey:k,ox:o.x||0,oy:o.y||0,strength:100,autoReach:true,live:true,depth:o.depth||'keep',on:true}}
async function preset(){var a=actor(),t=targetChar(a);if(!a||!t||a===t||!pose0(a))return;faceNo(a,t);var x=v('#interactionPreset','embrace'),g=150,j=[];if(x==='faceoff'){distNo(a,t,205);commit('faceoff');return}if(x==='handhold'){g=165;j=[['rHand','lHand',{depth:'front'}]]}if(x==='embrace'){g=112;j=[['rHand','waist',{depth:'front'}],['lHand','rUpperArm',{depth:'front'}]]}if(x==='grapple'){g=118;j=[['rHand','lUpperArm',{depth:'front'}],['lHand','rForearm',{depth:'front'}]]}if(x==='push'){g=145;j=[['rHand','chest',{depth:'front'}],['lHand','chest',{x:-25,depth:'front'}]]}if(x==='block'){g=155;j=[['rHand','rForearm',{depth:'front'}],['lHand','lForearm',{depth:'front'}]]}if(x==='kick'){g=165;j=[['rFoot','abdomen',{depth:'front'}]]}if(x==='support'){g=125;j=[['rHand','waist',{depth:'front'}],['lHand','lThigh',{depth:'front'}]]}distNo(a,t,g);for(var i=0;i<j.length;i++)await put(a,cc(a,t,j[i][0],j[i][1],j[i][2]),true);commit('v0.12 preset '+x)}
function selfPose(k){var a=actor();if(!a||!pose0(a))return;var j=k==='hips'?[['lHand','hips',{x:-35}],['rHand','hips',{x:35}]]:k==='head'?[['rHand','head',{x:25,y:-10}]]:[['lHand','chest',{x:-30}],['rHand','chest',{x:30}]];j.forEach(function(z){put(a,cc(a,a,z[0],z[1],z[2]),false)});commit('self contact')}
function pickMode(on){picking=!!on;var b=$('#interactionPickTargetBtn');if(b){b.classList.toggle('active-tool',picking);b.textContent=picking?bn('পয়েন্ট বাছা বন্ধ','Stop picking point'):bn('টার্গেটে ট্যাপ করে পয়েন্ট বাছুন','Tap target to pick point')}}
function nearest(t,l){var keys=Object.keys(joints).concat(['head','neck','chest','abdomen','waist','hips','lUpperArm','rUpperArm','lForearm','rForearm','lThigh','rThigh','lLowerLeg','rLowerLeg']),best='chest',bd=1e9;keys.forEach(function(k){var p=rp(t,k),d=Math.hypot((l.x-p.x)/Math.max(25,t.width*.12),(l.y-p.y)/Math.max(25,t.height*.12));if(d<bd){bd=d;best=k}});return best}
canvas.addEventListener('pointerdown',function(e){if(!picking)return;var a=actor(),t=a&&targetChar(a);if(!t)return;e.preventDefault();e.stopImmediatePropagation();var l=worldToLocal(t,screenToCanvas(e));if(l.x<0||l.y<0||l.x>t.width||l.y>t.height)return;var k=nearest(t,l),b=rp(t,k),ox=Math.max(-180,Math.min(180,Math.round(l.x-b.x))),oy=Math.max(-180,Math.min(180,Math.round(l.y-b.y)));$('#interactionTargetRegion').value=k;$('#interactionOffsetX').value=ox;$('#interactionOffsetY').value=oy;$('#interactionOffsetXOut').textContent=ox+'px';$('#interactionOffsetYOut').textContent=oy+'px';pickMode(false)},true);
function targets(){var s=$('#interactionTarget');if(!s)return;var a=actor(),cur=s.value;s.innerHTML='<option value="self">'+bn('নিজের শরীর (Self)','Own body (Self)')+'</option>';people().forEach(function(c){if(a&&c.id===a.id)return;var o=document.createElement('option');o.value=c.id;o.textContent=c.name;s.append(o)});if(Array.from(s.options).some(function(o){return o.value===cur}))s.value=cur}
function list(){var b=$('#interactionContactList'),a=actor(),cs=a&&a.interactionContacts||[];if(!b)return;b.innerHTML='';if(!cs.length){b.innerHTML='<div class="hint">'+bn('কোনো contact নেই।','No contacts yet.')+'</div>';return}cs.forEach(function(c){var t=state.layers.find(function(x){return x.id===c.targetId}),r=document.createElement('div');r.className='contact-row';var s=document.createElement('span');s.textContent=c.sourceKey+' → '+(t===a?bn('নিজের ','Self '):(t?t.name+' / ':''))+c.targetKey;var q=document.createElement('button');q.className='mini';q.textContent=c.on===false?bn('চালু','Enable'):bn('বন্ধ','Disable');q.onclick=function(){tog(c.id)};var d=document.createElement('button');d.className='mini danger';d.textContent=bn('মুছুন','Remove');d.onclick=function(){del(c.id)};r.append(s,q,d);b.append(r)})}
function status(){var a=actor(),e=$('#interactionStatus'),n=a&&a.interactionContacts?a.interactionContacts.length:0;if(e)e.textContent=n?bn(n+' contact · ঠিক '+health.ok+' · reach-limit '+health.limit,n+' contact(s) · OK '+health.ok+' · reach-limited '+health.limit):bn('কোনো interaction contact নেই','No interaction contacts')}
function overlay(){var a=actor(),cs=a&&a.interactionContacts||[];if(!a||!cs.length)return;ctx.save();ctx.lineWidth=2/zoom;ctx.setLineDash([7/zoom,5/zoom]);cs.forEach(function(c){if(c.on===false)return;var p=sp(a,c.sourceKey),t=target(a,c);if(!p||!t)return;var w=localToWorld(a,p);ctx.beginPath();ctx.strokeStyle='rgba(124,243,200,.9)';ctx.moveTo(w.x,w.y);ctx.lineTo(t.w.x,t.w.y);ctx.stroke()});ctx.restore()}
function mount(){if(!$('#interactionTarget'))return;targets();list();status();[['interactionPickTargetBtn',function(){pickMode(!picking)}],['interactionAddBtn',add],['interactionClearBtn',clear],['interactionFaceBtn',face],['interactionNearBtn',near],['interactionFrontBtn',function(){rel(true)}],['interactionBehindBtn',function(){rel(false)}],['interactionPresetBtn',preset],['selfHandsHipsBtn',function(){selfPose('hips')}],['selfHandHeadBtn',function(){selfPose('head')}],['selfHandsChestBtn',function(){selfPose('chest')}]].forEach(function(p){var e=$(p[0]);if(e&&!e.dataset.v12){e.dataset.v12='1';e.addEventListener('click',p[1])}});['interactionStrength','interactionOffsetX','interactionOffsetY','interactionDistance'].forEach(function(id){var e=$(id);if(e&&!e.dataset.v12o){e.dataset.v12o='1';e.addEventListener('input',function(){var o=$(id+'Out');if(o)o.textContent=e.value+(id==='interactionStrength'?'%':'px')})}});var old=$('#semanticContactBtn');if(old&&old.closest('.control-section'))old.closest('.control-section').style.display='none'}
var draw1=draw;draw=function(){solveAll();draw1();overlay();status()};var render1=renderUI;renderUI=function(){render1();mount();targets();list();status();if(window.PoseForgeI18n&&PoseForgeI18n.localizeTree)PoseForgeI18n.localizeTree(document.body)};
window.PoseForgeV012={add:add,solveAll:solveAll,clear:clear,preset:preset};
})();
