$('#saveCharacterBtn').addEventListener('click',async()=>{const l=selected();if(!l)return;const owner=l.kind==='character'?l:state.layers.find(x=>x.id===l.ownerId);if(!owner){say('Select a character or one of its parts.',true);return;}const pack=[owner,...state.layers.filter(x=>x.ownerId===owner.id)].map(cloneLayerForJSON);const item={id:uid('libchar'),name:$('#libraryName').value||owner.name,time:Date.now(),layers:pack};await dbPut('characters',item);await renderLibraries();say('Editable character saved to local library.');});
$('#savePoseBtn').addEventListener('click',async()=>{const l=selected();if(!l)return;const owner=l.kind==='character'?l:state.layers.find(x=>x.id===l.ownerId);if(!owner)return;const layers=[owner,...state.layers.filter(x=>x.ownerId===owner.id)].map(x=>({role:x.kind==='character'?'base':x.partRole,name:x.name,x:x.x-owner.x,y:x.y-owner.y,rotation:x.rotation-owner.rotation,scaleX:x.scaleX/(owner.scaleX||1),scaleY:x.scaleY/(owner.scaleY||1),bend:x.bend}));const item={id:uid('pose'),name:$('#libraryName').value||'Pose',time:Date.now(),layers};await dbPut('poses',item);await renderLibraries();say('Pose saved.');});
async function renderLibraries(){
 const cr=$('#characterLibrary'),pr=$('#poseLibrary');cr.innerHTML='';pr.innerHTML='';
 for(const it of (await dbAll('characters')).sort((a,b)=>b.time-a.time)){const d=document.createElement('div');d.className='library-entry';d.innerHTML=`<span>${escapeHtml(it.name)}</span>`;const add=document.createElement('button');add.className='mini';add.textContent='Add';add.onclick=async()=>{if(chars().length>=MAX_CHARACTERS){say('25-person active limit reached.',true);return;}const oldBase=it.layers.find(x=>x.kind==='character')||it.layers[0];const idMap={};for(const raw of it.layers){const n={...raw,id:uid(raw.kind==='character'?'char':'part'),x:raw.x+50,y:raw.y+50};idMap[raw.id]=n.id;n.image=await imageFromDataURL(n.src);state.layers.push(n);}for(const n of state.layers.slice(-it.layers.length)){if(n.ownerId&&idMap[n.ownerId])n.ownerId=idMap[n.ownerId];}state.selectedId=idMap[oldBase.id];pushHistory('library add');renderUI();draw();autoSave();};const del=document.createElement('button');del.className='mini';del.textContent='×';del.onclick=async()=>{await dbDelete('characters',it.id);renderLibraries();};d.append(add,del);cr.append(d);}
 for(const it of (await dbAll('poses')).sort((a,b)=>b.time-a.time)){const d=document.createElement('div');d.className='library-entry';d.innerHTML=`<span>${escapeHtml(it.name)}</span>`;const ap=document.createElement('button');ap.className='mini';ap.textContent='Apply';ap.onclick=()=>applyPose(it);const del=document.createElement('button');del.className='mini';del.textContent='×';del.onclick=async()=>{await dbDelete('poses',it.id);renderLibraries();};d.append(ap,del);pr.append(d);}
}
function applyPose(pose){const l=selected();if(!l)return;const owner=l.kind==='character'?l:state.layers.find(x=>x.id===l.ownerId);if(!owner)return;for(const spec of pose.layers){const target=spec.role==='base'?owner:state.layers.find(x=>x.ownerId===owner.id&&x.partRole===spec.role);if(!target)continue;if(spec.role==='base'){target.rotation+=spec.rotation;target.bend=spec.bend;continue;}target.x=owner.x+spec.x;target.y=owner.y+spec.y;target.rotation=owner.rotation+spec.rotation;target.scaleX=owner.scaleX*spec.scaleX;target.scaleY=owner.scaleY*spec.scaleY;target.bend=spec.bend;}pushHistory('pose apply');renderUI();draw();autoSave();}

for(const tab of document.querySelectorAll('.tab'))tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabpane').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('#tab-'+tab.dataset.tab).classList.add('active');});
$('#featherCtrl').addEventListener('input',()=>$('#featherOut').textContent=$('#featherCtrl').value+'px');
