$('#endpointUrl').value=localStorage.getItem('pf.endpoint')||'';
$('#endpointUrl').addEventListener('change',()=>{localStorage.setItem('pf.endpoint',$('#endpointUrl').value.trim());$('#onlineStatus').textContent=$('#endpointUrl').value.trim()?'Endpoint configured':'Endpoint not configured';});
async function selectedPayload(){const l=selected();if(!l)throw new Error('Select a layer first.');return{projectVersion:1,mode:$('#aiMode').value,layer:cloneLayerForJSON(l),image:l.src,canvas:{width:canvas.width,height:canvas.height},instruction:'Analyze this selected character/layer for editable pose and segmentation.'};}
$('#analyzeBtn').addEventListener('click',async()=>{try{const mode=$('#aiMode').value,cfg={url:$('#endpointUrl').value.trim(),token:$('#endpointToken').value};const out=mode==='offline'?await PoseForgeAI.offline.analyze(await selectedPayload()):await PoseForgeAI.online.analyze(cfg,await selectedPayload());const l=selected();if(l){l.aiAnalysis=out;pushHistory('AI analysis');renderUI();draw();autoSave();}say(`AI analysis ready: ${out.poses?.length||0} pose, ${out.faces?.length||0} face, ${out.hands?.length||0} hands.`);console.log('AI analysis',out);}catch(e){say(e.message,true);}});
$('#repairBtn').addEventListener('click',async()=>{if(window.PoseForgeRepairStudio?.open){window.PoseForgeRepairStudio.open();return;}try{const mode=$('#aiMode').value,cfg={url:$('#endpointUrl').value.trim(),token:$('#endpointToken').value};const payload=await selectedPayload();payload.instruction='Repair only the requested visible region while preserving identity/style.';const out=mode==='offline'?await PoseForgeAI.offline.repair(payload):await PoseForgeAI.online.repair(cfg,payload);const data=out.image||out.data_url||out.dataUrl;if(!data)throw new Error('AI response did not include image/data_url.');const src=data.startsWith('data:')?data:`data:image/png;base64,${data}`;const l=selected();l.src=src;l.image=await imageFromDataURL(src);l.width=l.image.width;l.height=l.image.height;pushHistory('AI repair');renderUI();draw();autoSave();say('AI repair applied.');}catch(e){say(e.message,true);}});

function setupKeyboard(){document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==='Delete')$('#deleteBtn').click();});}

(async function init(){draw();history=[{label:'initial',data:JSON.stringify(serializable())}];updateUndo();setCutButtons();syncControls();setupKeyboard();await renderLibraries();await renderSnapshots();$('#onlineStatus').textContent=$('#endpointUrl').value.trim()?'Endpoint configured':'Endpoint not configured';try{const s=await PoseForgeAI.offline.status();$('#offlineStatus').textContent=s.ready?'Ready: pose, face, hands, segmentation':(s.reason||'Offline AI unavailable');}catch(e){}setTimeout(()=>{if(innerWidth<980)fitCanvas();},40);})();
